import { ParticipantRecord } from '../types';
import { extractDDD, getUFInfoFromDDD } from './cleaners';

export const INITIAL_SAMPLE_PARTICIPANTS: ParticipantRecord[] = [
  {
    id: 'PART-001',
    nome: 'Carlos Eduardo Silveira',
    email: 'carlos.silveira@supermercadosbh.com.br',
    telefone: '(31) 99874-5521',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'Gerente Geral de Prevenção de Perdas',
    cargoNormalizado: 'Gerente Geral de Prevenção de Perdas',
    nivelHierarquico: 'Gerência',
    setorFuncional: 'Prevenção de Perdas & Riscos',
    empresa: 'Supermercados BH',
    empresaNormalizada: 'Supermercados BH',
    cidade: 'Santa Luzia',
    uf: 'MG',
    cnpj: '04.641.376/0001-36',
    isMatriz: true,
    razaoSocial: 'SUPERMERCADOS BH COMERCIO DE ALIMENTOS S.A.',
    nomeFantasia: 'SUPERMERCADOS BH',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 15.000.000.000 a R$ 20.000.000.000',
    faturamentoValor: 17000000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Comércio varejista de mercadorias em geral com predominância de produtos alimentícios - supermercados',
    naturezaJuridica: '205-4 - Sociedade Anônima Fechada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz validado e enriquecido via Econodata.',
    dataHoraConfirmacao: '2026-08-20 09:30:14',
  },
  {
    id: 'PART-002',
    nome: 'Ana Paula Mendonça',
    email: 'ana.mendonca@martminas.com.br',
    telefone: '(31) 98712-4433',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'Diretora de Operações e Riscos',
    cargoNormalizado: 'Diretora de Operações e Riscos',
    nivelHierarquico: 'Diretoria',
    setorFuncional: 'Prevenção de Perdas & Riscos',
    empresa: 'Mart Minas Atacado e Varejo',
    empresaNormalizada: 'Mart Minas',
    cidade: 'Contagem',
    uf: 'MG',
    cnpj: '04.407.497/0001-44',
    isMatriz: true,
    razaoSocial: 'MART MINAS DISTRIBUICAO LTDA',
    nomeFantasia: 'MART MINAS ATACADO E VAREJO',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 8.000.000.000 a R$ 12.000.000.000',
    faturamentoValor: 9500000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/01 - Hipermercados',
    naturezaJuridica: '206-2 - Sociedade Empresária Limitada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz validado e enriquecido via Econodata.',
    dataHoraConfirmacao: '2026-08-21 14:15:02',
  },
  {
    id: 'PART-003',
    nome: 'Rodrigo Alvarenga Castro',
    email: 'rodrigo.castro@supernosso.com.br',
    telefone: '(31) 99120-8899',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'Head de Segurança Patrimonial e Inteligência',
    cargoNormalizado: 'Head de Segurança Patrimonial e Inteligência',
    nivelHierarquico: 'Diretoria',
    setorFuncional: 'Segurança Patrimonial & Cibernética',
    empresa: 'Grupo Super Nosso',
    empresaNormalizada: 'Super Nosso',
    cidade: 'Contagem',
    uf: 'MG',
    cnpj: '02.434.908/0001-40',
    isMatriz: true,
    razaoSocial: 'SUPER NOSSO COMERCIO LTDA',
    nomeFantasia: 'SUPER NOSSO / APOIO MINEIRO',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 3.500.000.000 a R$ 5.000.000.000',
    faturamentoValor: 4200000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Supermercados',
    naturezaJuridica: '206-2 - Sociedade Empresária Limitada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz conferido.',
    dataHoraConfirmacao: '2026-08-22 10:45:30',
  },
  {
    id: 'PART-004',
    nome: 'Mariana Duarte Souza',
    email: 'mariana.duarte@verdemar.com.br',
    telefone: '(31) 98455-1122',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'Coordenadora de Auditoria e Inventários',
    cargoNormalizado: 'Coordenadora de Auditoria e Inventários',
    nivelHierarquico: 'Coordenação / Supervisão',
    setorFuncional: 'Auditoria & Compliance',
    empresa: 'Supermercado Verdemar',
    empresaNormalizada: 'Verdemar',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    cnpj: '00.417.857/0001-81',
    isMatriz: true,
    razaoSocial: 'VERDEMAR ALIMENTOS LTDA',
    nomeFantasia: 'SUPERMERCADO VERDEMAR',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 1.500.000.000 a R$ 2.500.000.000',
    faturamentoValor: 1800000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Supermercados',
    naturezaJuridica: '206-2 - Sociedade Empresária Limitada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz validado.',
    dataHoraConfirmacao: '2026-08-22 11:20:00',
  },
  {
    id: 'PART-005',
    nome: 'Fernando Guimarães Borges',
    email: 'fernando.borges@dmaonline.com.br',
    telefone: '(31) 97330-5544',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'Gerente de Prevenção e Auditoria de Estoque',
    cargoNormalizado: 'Gerente de Prevenção e Auditoria de Estoque',
    nivelHierarquico: 'Gerência',
    setorFuncional: 'Prevenção de Perdas & Riscos',
    empresa: 'DMA Distribuidora (EPA Supermercados)',
    empresaNormalizada: 'DMA Distribuidora S/A',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    cnpj: '21.050.413/0001-90',
    isMatriz: true,
    razaoSocial: 'DMA DISTRIBUIDORA S/A',
    nomeFantasia: 'EPA SUPERMERCADOS / MINEIRAO ATACAREJO',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 6.000.000.000 a R$ 8.500.000.000',
    faturamentoValor: 7200000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Supermercados',
    naturezaJuridica: '205-4 - Sociedade Anônima Fechada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz validado.',
    dataHoraConfirmacao: '2026-08-23 16:10:48',
  },
  {
    id: 'PART-006',
    nome: 'Luciana Pinheiro Resende',
    email: 'luciana.resende@bahamas.com.br',
    telefone: '(32) 99981-6789',
    ddd: '32',
    ufOrigemDDD: 'MG',
    cargo: 'Especialista em Gestão de Quebras e Acuracidade',
    cargoNormalizado: 'Especialista em Gestão de Quebras e Acuracidade',
    nivelHierarquico: 'Especialista / Consultor',
    setorFuncional: 'Prevenção de Perdas & Riscos',
    empresa: 'Grupo Bahamas',
    empresaNormalizada: 'Bahamas',
    cidade: 'Juiz de Fora',
    uf: 'MG',
    cnpj: '21.579.528/0001-09',
    isMatriz: true,
    razaoSocial: 'BAHAMAS DISTRIBUIDORA DE ALIMENTOS S.A.',
    nomeFantasia: 'SUPERMERCADOS BAHAMAS / BAHAMAS MIX',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 4.000.000.000 a R$ 6.000.000.000',
    faturamentoValor: 4800000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Supermercados',
    naturezaJuridica: '205-4 - Sociedade Anônima Fechada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz conferido.',
    dataHoraConfirmacao: '2026-08-24 08:50:11',
  },
  {
    id: 'PART-007',
    nome: 'Gabriel Moreira Lima',
    email: 'gabriel.lima@superabc.com.br',
    telefone: '(37) 99104-3321',
    ddd: '37',
    ufOrigemDDD: 'MG',
    cargo: 'Analista Sênior de Controles Internos',
    cargoNormalizado: 'Analista Sênior de Controles Internos',
    nivelHierarquico: 'Analista',
    setorFuncional: 'Auditoria & Compliance',
    empresa: 'Supermercados ABC',
    empresaNormalizada: 'Supermercados ABC',
    cidade: 'Divinópolis',
    uf: 'MG',
    cnpj: '20.590.237/0001-08',
    isMatriz: true,
    razaoSocial: 'ABC COMERCIO E DISTRIBUICAO LTDA',
    nomeFantasia: 'SUPERMERCADOS ABC',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Lucro Real',
    porteEmpresa: 'Grande Empresa',
    faturamento: 'R$ 2.800.000.000 a R$ 4.000.000.000',
    faturamentoValor: 3200000000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '4711-3/02 - Supermercados',
    naturezaJuridica: '206-2 - Sociedade Empresária Limitada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'CNPJ Matriz conferido.',
    dataHoraConfirmacao: '2026-08-24 11:05:22',
  },
  {
    id: 'PART-008',
    nome: 'Thiago Faria Santos',
    email: 'thiago.santos@strategicos.com.br',
    telefone: '(31) 98822-0011',
    ddd: '31',
    ufOrigemDDD: 'MG',
    cargo: 'CEO & Consultor Estratégico',
    cargoNormalizado: 'CEO & Consultor Estratégico',
    nivelHierarquico: 'C-Level / Presidência',
    setorFuncional: 'Geral / Executivo',
    empresa: 'Strategicos Group',
    empresaNormalizada: 'Strategicos Consultoria',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    cnpj: '35.819.421/0001-50',
    isMatriz: true,
    razaoSocial: 'STRATEGICOS CONSULTORIA EM GESTAO EMPRESARIAL LTDA',
    nomeFantasia: 'STRATEGICOS GROUP',
    situacaoCadastral: 'ATIVA',
    regimeTributario: 'Simples Nacional / Lucro Presumido',
    porteEmpresa: 'Empresa de Pequeno Porte (EPP)',
    faturamento: 'R$ 1.200.000 a R$ 3.600.000',
    faturamentoValor: 2400000,
    faturamentoOrigem: 'Econodata Estimado',
    cnae: '7020-4/00 - Consultoria em Gestão Empresarial',
    naturezaJuridica: '206-2 - Sociedade Empresária Limitada',
    statusEnriquecimento: 'CONSULTADO',
    origemIdentificacao: 'Base Cadastral Corporativa Oficial',
    observacoes: 'Apoio e Curadoria Técnica do 6º Fórum ACESU.',
    dataHoraConfirmacao: '2026-08-25 15:30:00',
  }
];
